---
---
- name: Update and install dependencies
  apt:
    name: "{{ docker_dependencies }}"
    update_cache: yes

- name: Add key repository
  apt_key:
    url: "{{ docker_key_url }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker

- name: Install Docker CE
  apt:
    name: "{{ docker_package }}"
    state: present

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true

