---
- name: "configure pg_hba.conf"
  template:
    src: templates/pg_hba.conf.j2
    dest: "{{ pgsql_data_dir }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600
  notify: "restart postgresql"

    