Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    SERVERS = 3
    BRIDGE = "Intel(R) Wi-Fi 6 AX200 160MHz"
  
    def create_host(config, hostname, ip)
      config.vm.define hostname do |host|
        host.vm.network "private_network", ip: ip
        host.vm.network "public_network", bridge: BRIDGE
        host.vm.hostname = hostname
        
        host.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install -y python3-minimal openssh-server
          systemctl enable ssh
          systemctl start ssh
        SHELL
        yield host if block_given?
      end
    end
  
    (1..SERVERS).each do |machine_id|
      create_host(config, "srv#{machine_id}", "192.168.56.#{200+machine_id}")
    end
  
  end