---
- name: "Install Nginx to web hosts"
  hosts: web
  become: true

  roles:
    - nginx

  tasks:
    - name: "Copy Nginx Config File"
      template:
        src: /home/vagrant/iac/lab3/files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: "Restart Nginx"
      service:
        name: nginx
        state: restarted

    - name: "Enable Configuration"
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: "Restart Nginx again"
      service:
        name: nginx
        state: restarted

- name: "Install Docker to app hosts"
  hosts: "app"
  become: true

  roles:
    - docker
  vars:
    - docker_user: "vagrant"
  tasks:
    - name: "Run Django Application"
      docker_container:
        name: django-app
        image: timurbabs/django:latest
        state: started
        ports:
          - "8000:8000"
