roles:
  - src: git+https://gitlab.com/devops-itmo2/docker-role.git
    version: main
    name: docker
    
  - src: git+https://gitlab.com/devops-itmo2/nginx-role.git
    version: main
    name: nginx
