---
docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

docker_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
docker_package: docker-ce

